---
- include_tasks: yum/add_nginx_repo.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: apt/install_nginx.yml
  when: ansible_os_family == 'Debian'

- include_tasks: yum/install_nginx.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure configuration directorie exists
  file:
    path: '{{ item }}'
    state: directory
  become: true
  with_items:
    - /etc/nginx/sites-enabled
    - /etc/nginx/sites-available

- name: Upload default confing
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true
  notify:
    - restart nginx
