---
- name: Initial setups
  hosts: production
  gather_facts: no

  roles:
    - setup

- name: Configure Staging server
  hosts: production

  roles:
    - rails-config
    - nginx
    - rbenv
    - mysql
