---
- name: Initial setup
  hosts: vagrant
  gather_facts: no

  roles:
    - setup

- name: Configure Staging server
  hosts: vagrant

  roles:
    - rails-config
    - nginx
    - rbenv
    - mysql
