---
- name: Add nodejs ppa {{ ansible_os_family }}
  get_url: 
    url: https://rpm.nodesource.com/setup_8.x
    dest: /tmp/nodejs.sh

- name: Execute nodejs ppa installer
  command: sh /tmp/nodejs.sh
  become: true

- name: Install nodejs {{ ansible_os_family }}
  yum:
    name: nodejs
    state: installed
    update_cache: yes
  become: true
