---
- include_tasks: yum/add_mysql_repo.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: apt/install_mysql.yml
  when: ansible_os_family == 'Debian'

- include_tasks: yum/install_mysql.yml
  when: ansible_os_family == 'RedHat'

- name: Create MySQL server user for localhost
  mysql_user:
    user: '{{ item }}'
    password: '{{ mysql_user_password }}'
    priv: '*.*:ALL,GRANT'
    state: present
    login_password: '{{ mysql_root_password }}'
    login_user: root
  with_items:
    - "{{ mysql_user }}"

- name: Delete anonymous MySQL server user for localhost
  mysql_user:
    user: '{{ item }}'
    state: absent
    login_password: '{{ mysql_root_password }}'
    login_user: root
  with_items:
    - ''

- name: Removes the MySQL test database
  mysql_db:
    db: test
    state: absent
    login_password: '{{ mysql_root_password }}'
    login_user: root

- name: Create the MySQL database - {{ app_name }}_{{ app_env }}
  mysql_db:
    db: '{{ app_name }}_{{ app_env }}'
    state: present
    login_password: '{{ mysql_root_password }}'
    login_user: root

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  become: true
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes

- include_tasks: apt/install_lib.yml
  when: ansible_os_family == 'Debian'

- include_tasks: yum/install_lib.yml
  when: ansible_os_family == 'RedHat'
