---
- name: Set MySQL root password before installing
  debconf:
    name: mysql-server
    question: 'mysql-server/root_password'
    value: '{{mysql_root_password | quote}}'
    vtype: password
  become: true

- name: Confirm MySQL root password before installing
  debconf:
    name: mysql-server
    question: 'mysql-server/root_password_again'
    value: '{{mysql_root_password | quote}}'
    vtype: password
  become: true

- name: Install MySQL
  apt:
    package: '{{ item }}'
    state: installed
    force: true
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
  become: true

- name: Secures the MySQL root user
  mysql_user:
    user: root
    password: '{{ mysql_root_password }}'
    host: '{{ item }}'
    login_password: '{{ mysql_root_password }}'
    login_user: root
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"
