---
- name: Install library
  apt:
    package: '{{ item }}'
    state: installed
    force: true
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - libmysqlclient-dev
  become: true