---
- name: Check for {{ ruby_version }}
  stat:
    path: '{{ rbenv_path }}/versions/{{ ruby_version }}'
  register: ruby
  ignore_errors: yes

- block:
  - name: Install ruby {{ ruby_version }}
    raw: 'TMPDIR=~/tmp MAKE_OPTS=-j4 RBENV_ROOT={{ rbenv_path }} {{ rbenv_path }}/bin/rbenv install {{ ruby_version }}'
    become: true
    become_user: '{{ ansible_user_id }}'

  - name: Rehash ruby installations
    raw: 'RBENV_ROOT={{ rbenv_path }} {{ rbenv_path }}/bin/rbenv rehash'
    become: true
    become_user: '{{ ansible_user_id }}'

  when: ruby.stat.exists == false
